# Generated by Django 4.2 on 2026-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_original', models.ImageField(upload_to='uploads/')),
                ('imagem_processada', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('rosto_detectado', models.BooleanField(default=False)),
            ],
        ),
    ]
